@extends('layouts.app')

@section('content')
<x-hero-page-default-section title="Политика приватности" description="Cтраница политики" background-image="bg-auth" />

<section class="py-[4rem]">
    <div class="container">
        <div class="w-10/12 mx-auto">
            <p class="text-content">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis.</p>
            <p class="text-content">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis.</p>
            <p class="text-content">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis.</p>
            <p class="text-content">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis.</p>
            <p class="text-content">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam, alias enim! Similique ipsum quod error, itaque nesciunt, repellendus dolores unde eos voluptas ipsam, nihil excepturi aliquid tenetur nostrum at perferendis.</p>
        </div>
    </div>
</section>

@endsection